gemAuthor: "Trieve"
gemAuthorEmail: "developers@trieve.ai"
gemDescription: "Trieve Ruby API client"
gemHomepage: "https://trieve.ai"
gemLicense: "MIT"
gemName: "trieve_ruby_client"
gemSummary: "Trieve Ruby API client"
gemVersion: "0.3.4"
moduleName: "TrieveRubyClient"