=begin
#Trieve API

#Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

The version of the OpenAPI document: 0.11.0
Contact: developers@trieve.ai
Generated by: https://openapi-generator.tech
Generator version: 7.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for TrieveRubyClient::AnalyticsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AnalyticsApi' do
  before do
    # run before each test
    @api_instance = TrieveRubyClient::AnalyticsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AnalyticsApi' do
    it 'should create an instance of AnalyticsApi' do
      expect(@api_instance).to be_instance_of(TrieveRubyClient::AnalyticsApi)
    end
  end

  # unit tests for get_cluster_analytics
  # Get Cluster Analytics
  # This route allows you to view the cluster analytics for a dataset.
  # @param tr_dataset The dataset id to use for the request
  # @param cluster_analytics JSON request payload to filter the graph
  # @param [Hash] opts the optional parameters
  # @return [ClusterAnalyticsResponse]
  describe 'get_cluster_analytics test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_rag_analytics
  # Get RAG Analytics
  # This route allows you to view the RAG analytics for a dataset.
  # @param tr_dataset The dataset id to use for the request
  # @param rag_analytics JSON request payload to filter the graph
  # @param [Hash] opts the optional parameters
  # @return [RAGAnalyticsResponse]
  describe 'get_rag_analytics test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_recommendation_analytics
  # Get Recommendation Analytics
  # This route allows you to view the recommendation analytics for a dataset.
  # @param tr_dataset The dataset id to use for the request
  # @param recommendation_analytics JSON request payload to filter the graph
  # @param [Hash] opts the optional parameters
  # @return [RecommendationAnalyticsResponse]
  describe 'get_recommendation_analytics test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_search_analytics
  # Get Search Analytics
  # This route allows you to view the search analytics for a dataset.
  # @param tr_dataset The dataset id to use for the request
  # @param search_analytics JSON request payload to filter the graph
  # @param [Hash] opts the optional parameters
  # @return [SearchAnalyticsResponse]
  describe 'get_search_analytics test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
