=begin
#Trieve API

#Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

The version of the OpenAPI document: 0.5.0
Contact: developers@trieve.ai
Generated by: https://openapi-generator.tech
Generator version: 7.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for TrieveRubyClient::AuthApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AuthApi' do
  before do
    # run before each test
    @api_instance = TrieveRubyClient::AuthApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AuthApi' do
    it 'should create an instance of AuthApi' do
      expect(@api_instance).to be_instance_of(TrieveRubyClient::AuthApi)
    end
  end

  # unit tests for callback
  # OpenID Connect callback
  # OpenID Connect callback  This is the callback route for the OAuth provider, it should not be called directly. Redirects to browser with set-cookie header.
  # @param [Hash] opts the optional parameters
  # @return [SlimUser]
  describe 'callback test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_me
  # Get Me
  # Get Me  Get the user corresponding to your current auth credentials.
  # @param [Hash] opts the optional parameters
  # @return [SlimUser]
  describe 'get_me test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for login
  # Login
  # Login  This will redirect you to the OAuth provider for authentication with email/pass, SSO, Google, Github, etc.
  # @param content Query parameters for login to be included as kv pairs after ? on the request URL.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'login test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for logout
  # Logout
  # Logout  Invalidate your current auth credential stored typically stored in a cookie. This does not invalidate your API key.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'logout test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
