=begin
#trieve-server

#Trieve REST API OpenAPI Documentation

The version of the OpenAPI document: 0.3.3

Generated by: https://openapi-generator.tech
Generator version: 7.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::UserApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'UserApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::UserApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UserApi' do
    it 'should create an instance of UserApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::UserApi)
    end
  end

  # unit tests for delete_user_api_key
  # delete_user_api_key
  # delete_user_api_key  Delete an api key for the auth&#39;ed user.
  # @param delete_user_api_key_request JSON request payload to delete a user api key
  # @param [Hash] opts the optional parameters
  # @return [Array<ApiKeyDTO>]
  describe 'delete_user_api_key test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for set_user_api_key
  # set_user_api_key
  # set_user_api_key  Create a new api key for the auth&#39;ed user. Successful response will contain the newly created api key. If a write role is assigned the api key will have permission level of the auth&#39;ed user who calls this endpoint.
  # @param set_user_api_key_request JSON request payload to create a new user api key
  # @param [Hash] opts the optional parameters
  # @return [SetUserApiKeyResponse]
  describe 'set_user_api_key test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_user
  # update_user
  # update_user  Update a user&#39;s information. If the user_id is not provided, the auth&#39;ed user will be updated. If the user_id is provided, the auth&#39;ed user must be an admin (1) or owner (2) of the organization.
  # @param update_user_data JSON request payload to update user information for the auth&#39;ed user
  # @param [Hash] opts the optional parameters
  # @return [SlimUser]
  describe 'update_user test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
