=begin
#Trieve API

#Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

The version of the OpenAPI document: 0.11.0
Contact: developers@trieve.ai
Generated by: https://openapi-generator.tech
Generator version: 7.4.0

=end

require 'date'
require 'time'

module TrieveRubyClient
  class EventTypeRequest
    FILE_UPLOADED = "file_uploaded".freeze
    FILE_UPLOAD_FAILED = "file_upload_failed".freeze
    CHUNKS_UPLOADED = "chunks_uploaded".freeze
    CHUNK_ACTION_FAILED = "chunk_action_failed".freeze
    CHUNK_UPDATED = "chunk_updated".freeze
    BULK_CHUNKS_DELETED = "bulk_chunks_deleted".freeze
    DATASET_DELETE_FAILED = "dataset_delete_failed".freeze
    QDRANT_UPLOAD_FAILED = "qdrant_upload_failed".freeze
    BULK_CHUNK_UPLOAD_FAILED = "bulk_chunk_upload_failed".freeze
    GROUP_CHUNKS_UPDATED = "group_chunks_updated".freeze
    GROUP_CHUNKS_ACTION_FAILED = "group_chunks_action_failed".freeze

    def self.all_vars
      @all_vars ||= [FILE_UPLOADED, FILE_UPLOAD_FAILED, CHUNKS_UPLOADED, CHUNK_ACTION_FAILED, CHUNK_UPDATED, BULK_CHUNKS_DELETED, DATASET_DELETE_FAILED, QDRANT_UPLOAD_FAILED, BULK_CHUNK_UPLOAD_FAILED, GROUP_CHUNKS_UPDATED, GROUP_CHUNKS_ACTION_FAILED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if EventTypeRequest.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #EventTypeRequest"
    end
  end
end
