=begin
#Trieve API

#Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

The version of the OpenAPI document: 0.11.0
Contact: developers@trieve.ai
Generated by: https://openapi-generator.tech
Generator version: 7.4.0

=end

require 'date'
require 'time'

module TrieveRubyClient
  class RecommendChunksRequest
    attr_accessor :filters

    # The number of chunks to return. This is the number of chunks which will be returned in the response. The default is 10.
    attr_accessor :limit

    # The ids of the chunks to be used as negative examples for the recommendation. The chunks in this array will be used to filter out similar chunks.
    attr_accessor :negative_chunk_ids

    # The tracking_ids of the chunks to be used as negative examples for the recommendation. The chunks in this array will be used to filter out similar chunks.
    attr_accessor :negative_tracking_ids

    # The ids of the chunks to be used as positive examples for the recommendation. The chunks in this array will be used to find similar chunks.
    attr_accessor :positive_chunk_ids

    # The tracking_ids of the chunks to be used as positive examples for the recommendation. The chunks in this array will be used to find similar chunks.
    attr_accessor :positive_tracking_ids

    attr_accessor :recommend_type

    # Set slim_chunks to true to avoid returning the content and chunk_html of the chunks. This is useful for when you want to reduce amount of data over the wire for latency improvement (typicall 10-50ms). Default is false.
    attr_accessor :slim_chunks

    attr_accessor :strategy

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'filters' => :'filters',
        :'limit' => :'limit',
        :'negative_chunk_ids' => :'negative_chunk_ids',
        :'negative_tracking_ids' => :'negative_tracking_ids',
        :'positive_chunk_ids' => :'positive_chunk_ids',
        :'positive_tracking_ids' => :'positive_tracking_ids',
        :'recommend_type' => :'recommend_type',
        :'slim_chunks' => :'slim_chunks',
        :'strategy' => :'strategy'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'filters' => :'ChunkFilter',
        :'limit' => :'Integer',
        :'negative_chunk_ids' => :'Array<String>',
        :'negative_tracking_ids' => :'Array<String>',
        :'positive_chunk_ids' => :'Array<String>',
        :'positive_tracking_ids' => :'Array<String>',
        :'recommend_type' => :'RecommendType',
        :'slim_chunks' => :'Boolean',
        :'strategy' => :'RecommendationStrategy'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'filters',
        :'limit',
        :'negative_chunk_ids',
        :'negative_tracking_ids',
        :'positive_chunk_ids',
        :'positive_tracking_ids',
        :'recommend_type',
        :'slim_chunks',
        :'strategy'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TrieveRubyClient::RecommendChunksRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TrieveRubyClient::RecommendChunksRequest`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'filters')
        self.filters = attributes[:'filters']
      end

      if attributes.key?(:'limit')
        self.limit = attributes[:'limit']
      end

      if attributes.key?(:'negative_chunk_ids')
        if (value = attributes[:'negative_chunk_ids']).is_a?(Array)
          self.negative_chunk_ids = value
        end
      end

      if attributes.key?(:'negative_tracking_ids')
        if (value = attributes[:'negative_tracking_ids']).is_a?(Array)
          self.negative_tracking_ids = value
        end
      end

      if attributes.key?(:'positive_chunk_ids')
        if (value = attributes[:'positive_chunk_ids']).is_a?(Array)
          self.positive_chunk_ids = value
        end
      end

      if attributes.key?(:'positive_tracking_ids')
        if (value = attributes[:'positive_tracking_ids']).is_a?(Array)
          self.positive_tracking_ids = value
        end
      end

      if attributes.key?(:'recommend_type')
        self.recommend_type = attributes[:'recommend_type']
      end

      if attributes.key?(:'slim_chunks')
        self.slim_chunks = attributes[:'slim_chunks']
      end

      if attributes.key?(:'strategy')
        self.strategy = attributes[:'strategy']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@limit.nil? && @limit < 0
        invalid_properties.push('invalid value for "limit", must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@limit.nil? && @limit < 0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] limit Value to be assigned
    def limit=(limit)
      if !limit.nil? && limit < 0
        fail ArgumentError, 'invalid value for "limit", must be greater than or equal to 0.'
      end

      @limit = limit
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          filters == o.filters &&
          limit == o.limit &&
          negative_chunk_ids == o.negative_chunk_ids &&
          negative_tracking_ids == o.negative_tracking_ids &&
          positive_chunk_ids == o.positive_chunk_ids &&
          positive_tracking_ids == o.positive_tracking_ids &&
          recommend_type == o.recommend_type &&
          slim_chunks == o.slim_chunks &&
          strategy == o.strategy
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [filters, limit, negative_chunk_ids, negative_tracking_ids, positive_chunk_ids, positive_tracking_ids, recommend_type, slim_chunks, strategy].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = TrieveRubyClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
