=begin
#Trieve API

#Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

The version of the OpenAPI document: 0.11.0
Contact: developers@trieve.ai
Generated by: https://openapi-generator.tech
Generator version: 7.4.0

=end

require 'date'
require 'time'

module TrieveRubyClient
  class SearchType
    SEARCH = "search".freeze
    AUTOCOMPLETE = "autocomplete".freeze
    SEARCH_OVER_GROUPS = "search_over_groups".freeze
    SEARCH_WITHIN_GROUPS = "search_within_groups".freeze

    def self.all_vars
      @all_vars ||= [SEARCH, AUTOCOMPLETE, SEARCH_OVER_GROUPS, SEARCH_WITHIN_GROUPS].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if SearchType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #SearchType"
    end
  end
end
