=begin
#Trieve API

#Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

The version of the OpenAPI document: 0.11.0
Contact: developers@trieve.ai
Generated by: https://openapi-generator.tech
Generator version: 7.4.0

=end

require 'date'
require 'time'

module TrieveRubyClient
  class SearchMethod
    FULL_TEXT = "full_text".freeze
    SEMANTIC = "semantic".freeze
    HYBRID = "hybrid".freeze
    BM25 = "bm25".freeze

    def self.all_vars
      @all_vars ||= [FULL_TEXT, SEMANTIC, HYBRID, BM25].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if SearchMethod.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #SearchMethod"
    end
  end
end
