=begin
#trieve-server

#Trieve REST API OpenAPI Documentation

The version of the OpenAPI document: 0.3.3

Generated by: https://openapi-generator.tech
Generator version: 7.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::AddChunkToGroupData
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::AddChunkToGroupData do
  let(:instance) { OpenapiClient::AddChunkToGroupData.new }

  describe 'test an instance of AddChunkToGroupData' do
    it 'should create an instance of AddChunkToGroupData' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::AddChunkToGroupData)
    end
  end

  describe 'test attribute "chunk_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
