=begin
#Trieve API

#Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

The version of the OpenAPI document: 0.6.2
Contact: developers@trieve.ai
Generated by: https://openapi-generator.tech
Generator version: 7.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TrieveRubyClient::GroupScoreChunk
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TrieveRubyClient::GroupScoreChunk do
  let(:instance) { TrieveRubyClient::GroupScoreChunk.new }

  describe 'test an instance of GroupScoreChunk' do
    it 'should create an instance of GroupScoreChunk' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(TrieveRubyClient::GroupScoreChunk)
    end
  end

  describe 'test attribute "group_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "group_tracking_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "metadata"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
