=begin
#Trieve API

#Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

The version of the OpenAPI document: 0.5.7
Contact: developers@trieve.ai
Generated by: https://openapi-generator.tech
Generator version: 7.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TrieveRubyClient::GroupSlimChunksDTO
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TrieveRubyClient::GroupSlimChunksDTO do
  let(:instance) { TrieveRubyClient::GroupSlimChunksDTO.new }

  describe 'test an instance of GroupSlimChunksDTO' do
    it 'should create an instance of GroupSlimChunksDTO' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(TrieveRubyClient::GroupSlimChunksDTO)
    end
  end

  describe 'test attribute "group_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "metadata"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
