=begin
#Trieve API

#Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

The version of the OpenAPI document: 0.7.5
Contact: developers@trieve.ai
Generated by: https://openapi-generator.tech
Generator version: 7.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TrieveRubyClient::LocationBoundingBox
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TrieveRubyClient::LocationBoundingBox do
  let(:instance) { TrieveRubyClient::LocationBoundingBox.new }

  describe 'test an instance of LocationBoundingBox' do
    it 'should create an instance of LocationBoundingBox' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(TrieveRubyClient::LocationBoundingBox)
    end
  end

  describe 'test attribute "bottom_right"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "top_left"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
