=begin
#Trieve API

#Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

The version of the OpenAPI document: 0.11.0
Contact: developers@trieve.ai
Generated by: https://openapi-generator.tech
Generator version: 7.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TrieveRubyClient::SearchAnalyticsFilter
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TrieveRubyClient::SearchAnalyticsFilter do
  let(:instance) { TrieveRubyClient::SearchAnalyticsFilter.new }

  describe 'test an instance of SearchAnalyticsFilter' do
    it 'should create an instance of SearchAnalyticsFilter' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(TrieveRubyClient::SearchAnalyticsFilter)
    end
  end

  describe 'test attribute "date_range"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "search_method"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "search_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
