=begin
#Trieve API

#Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

The version of the OpenAPI document: 0.11.0
Contact: developers@trieve.ai
Generated by: https://openapi-generator.tech
Generator version: 7.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TrieveRubyClient::SortOrder
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TrieveRubyClient::SortOrder do
  let(:instance) { TrieveRubyClient::SortOrder.new }

  describe 'test an instance of SortOrder' do
    it 'should create an instance of SortOrder' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(TrieveRubyClient::SortOrder)
    end
  end

end
