=begin
#trieve-server

#Trieve REST API OpenAPI Documentation

The version of the OpenAPI document: 0.3.3

Generated by: https://openapi-generator.tech
Generator version: 7.4.0

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/add_chunk_to_group_data'
require 'openapi_client/models/api_key_dto'
require 'openapi_client/models/bookmark_data'
require 'openapi_client/models/bookmark_group_result'
require 'openapi_client/models/chat_message_proxy'
require 'openapi_client/models/chunk_filter'
require 'openapi_client/models/chunk_group'
require 'openapi_client/models/chunk_group_and_file'
require 'openapi_client/models/chunk_metadata'
require 'openapi_client/models/chunk_metadata_with_file_data'
require 'openapi_client/models/client_dataset_configuration'
require 'openapi_client/models/create_chunk_data'
require 'openapi_client/models/create_chunk_group_data'
require 'openapi_client/models/create_dataset_request'
require 'openapi_client/models/create_message_data'
require 'openapi_client/models/create_organization_data'
require 'openapi_client/models/create_topic_data'
require 'openapi_client/models/dataset'
require 'openapi_client/models/dataset_and_usage'
require 'openapi_client/models/dataset_dto'
require 'openapi_client/models/dataset_usage_count'
require 'openapi_client/models/delete_dataset_request'
require 'openapi_client/models/delete_topic_data'
require 'openapi_client/models/delete_user_api_key_request'
require 'openapi_client/models/edit_message_data'
require 'openapi_client/models/error_response_body'
require 'openapi_client/models/event'
require 'openapi_client/models/event_return'
require 'openapi_client/models/field_condition'
require 'openapi_client/models/file'
require 'openapi_client/models/file_dto'
require 'openapi_client/models/generate_chunks_request'
require 'openapi_client/models/get_groups_for_chunks_data'
require 'openapi_client/models/group_data'
require 'openapi_client/models/group_score_chunk_dto'
require 'openapi_client/models/invitation_data'
require 'openapi_client/models/match_condition'
require 'openapi_client/models/message'
require 'openapi_client/models/organization'
require 'openapi_client/models/organization_usage_count'
require 'openapi_client/models/range'
require 'openapi_client/models/reccomend_group_chunks_request'
require 'openapi_client/models/recommend_chunks_request'
require 'openapi_client/models/regenerate_message_data'
require 'openapi_client/models/return_queued_chunk'
require 'openapi_client/models/score_chunk_dto'
require 'openapi_client/models/search_chunk_data'
require 'openapi_client/models/search_chunk_query_response_body'
require 'openapi_client/models/search_groups_result'
require 'openapi_client/models/search_over_groups_data'
require 'openapi_client/models/search_over_groups_response_body'
require 'openapi_client/models/search_within_group_data'
require 'openapi_client/models/set_user_api_key_request'
require 'openapi_client/models/set_user_api_key_response'
require 'openapi_client/models/slim_group'
require 'openapi_client/models/slim_user'
require 'openapi_client/models/stripe_plan'
require 'openapi_client/models/stripe_subscription'
require 'openapi_client/models/suggested_queries_request'
require 'openapi_client/models/suggested_queries_response'
require 'openapi_client/models/topic'
require 'openapi_client/models/update_chunk_by_tracking_id_data'
require 'openapi_client/models/update_chunk_data'
require 'openapi_client/models/update_chunk_group_data'
require 'openapi_client/models/update_dataset_request'
require 'openapi_client/models/update_group_by_tracking_id_data'
require 'openapi_client/models/update_organization_data'
require 'openapi_client/models/update_topic_data'
require 'openapi_client/models/update_user_data'
require 'openapi_client/models/upload_file_data'
require 'openapi_client/models/upload_file_result'
require 'openapi_client/models/user_organization'

# APIs
require 'openapi_client/api/auth_api'
require 'openapi_client/api/chunk_api'
require 'openapi_client/api/chunk_group_api'
require 'openapi_client/api/dataset_api'
require 'openapi_client/api/events_api'
require 'openapi_client/api/file_api'
require 'openapi_client/api/health_api'
require 'openapi_client/api/invitation_api'
require 'openapi_client/api/message_api'
require 'openapi_client/api/organization_api'
require 'openapi_client/api/stripe_api'
require 'openapi_client/api/topic_api'
require 'openapi_client/api/user_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
